#!/usr/bin/env ruby
#
# $Id: armitage 11571 2011-01-13 16:04:42Z egypt $
#
# Ruby front-end to the Armitage Java user interface
#
# $Revision: 11571 $
#

msfbase = __FILE__
while File.symlink?(msfbase)
	msfbase = File.expand_path(File.readlink(msfbase), File.dirname(msfbase))
end

if RUBY_PLATFORM =~ /mswin|mingw/i
	exec "javaw", "-jar", "#{File.dirname(msfbase)}/data/armitage/armitage.jar", *ARGV
else
	exec "java", "-jar", "#{File.dirname(msfbase)}/data/armitage/armitage.jar", *ARGV
end
